# Tugas

1. Buatlah model klasifikasi dengan menggunakan SVM untuk data suara, voice.csv. 

2. Buatlah model klasfikasi Multinomial Naive Bayes dengan ketentuan,

- Menggunakan data spam.csv

- Fitur CountVectorizer dengan mengaktifkan stop_words

- Evaluasi hasilnya


3. Buatlah model klasfikasi Multinomial Naive Bayes dengan ketentuan,

- Menggunakan data spam.csv

- Fitur TF-IDF dengan mengaktifkan stop_words

- Evaluasi hasilnya dan bandingkan dengan hasil pada Tugas no 2.


    Berikan kesimpulan fitur mana yang terbaik pada kasus data spam.csv

**Jawab**

<h2> 1. Model Klasifikasi menggunakan SVM pada Data Suara, coice.csv </h2>

In [13]:
# import library
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats
import seaborn as sns
import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# baca data dari file CSV
data = pd.read_csv('../data/voice.csv')

# melihat beberapa data awal
data.head()

meanfreq        sd    median       Q25       Q75       IQR       skew  \
0  0.059781  0.064241  0.032027  0.015071  0.090193  0.075122  12.863462   
1  0.066009  0.067310  0.040229  0.019414  0.092666  0.073252  22.423285   
2  0.077316  0.083829  0.036718  0.008701  0.131908  0.123207  30.757155   
3  0.151228  0.072111  0.158011  0.096582  0.207955  0.111374   1.232831   
4  0.135120  0.079146  0.124656  0.078720  0.206045  0.127325   1.101174   

          kurt    sp.ent       sfm  ...  centroid   meanfun    minfun  \
0   274.402906  0.893369  0.491918  ...  0.059781  0.084279  0.015702   
1   634.613855  0.892193  0.513724  ...  0.066009  0.107937  0.015826   
2  1024.927705  0.846389  0.478905  ...  0.077316  0.098706  0.015656   
3     4.177296  0.963322  0.727232  ...  0.151228  0.088965  0.017798   
4     4.333713  0.971955  0.783568  ...  0.135120  0.106398  0.016931   

     maxfun   meandom    mindom    maxdom   dfrange   modindx  label  
0  0.275862  0.007812  0.007812  0.007812  0.000000  0.000000   male  
1  0.250000  0.009014  0.007812  0.054688  0.046875  0.052632   male  
2  0.271186  0.007990  0.007812  0.015625  0.007812  0.046512   male  
3  0.250000  0.201497  0.007812  0.562500  0.554688  0.247119   male  
4  0.266667  0.712812  0.007812  5.484375  5.476562  0.208274   male  

[5 rows x 21 columns]

<h4>Melakukan encoding data dan membagi menjadi atribut dan target</h4>

In [3]:
# Melakukan encoding male dan female
label_encoder = LabelEncoder()
data['label'] = label_encoder.fit_transform(data['label'])

# Memisahkan antara fitur dan targetnya
X = data.drop('label', axis=1)
y = data['label']

In [4]:
# Membagi data menjadi data training (80%) dan data testing (20%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

<h4> Membuat Model SVM</h4>

In [5]:
# Membuat model SVM 
svm_model = SVC(kernel='linear', random_state=42)

<h4>Melakukan training data SVM</h4>

In [6]:
# Melatih model SVM
svm_model.fit(X_train, y_train)

SVC(kernel='linear', random_state=42)

<h4> Evaluasi Model SVM<>

In [7]:
# Memprediksi label untuk data pengujian
y_pred = svm_model.predict(X_test)

# Mengukur akurasi model
akurasi = accuracy_score(y_test, y_pred)
print("Akurasi Model SVM:", akurasi)

# Menampilkan laporan klasifikasi
print("Klasifikasi:")
print(classification_report(y_test, y_pred))

# Menampilkan matriks konfusi
print("Matriks Konfusi:")
print(confusion_matrix(y_test, y_pred))

Akurasi Model SVM: 0.9416403785488959
Klasifikasi:
              precision    recall  f1-score   support

           0       0.98      0.89      0.93       297
           1       0.91      0.99      0.95       337

    accuracy                           0.94       634
   macro avg       0.95      0.94      0.94       634
weighted avg       0.94      0.94      0.94       634

Matriks Konfusi:
[[265  32]
 [  5 332]]


<h4> Akurasi Model SVM terhadap Label Sebenarnya dan Hasil Prediksi </h4>

In [8]:
# Hitung akurasi
accuracy = accuracy_score(y_test, y_pred)

# Cetak hasil akurasi
print(f'Skor Akurasi : {int(accuracy * 100)}%')

Skor Akurasi : 94%


<h2>2. Model klasfikasi Multinomial Naive Bayes</h2>

In [18]:
# baca file CSV
df = pd.read_csv('../data/spam.csv', encoding='latin-1') 
df.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

<h4>Rename pada Nama Kolom v1 dan v2</h4>

In [19]:
# Drop 3 kolom terakhir dengan fungsi iloc
df = df.drop(df.iloc[:,2:], axis=1)

# rename kolom v1 dan v2
new_cols = {
    'v1': 'Labels',
    'v2': 'Message'
}

# Rename nama kolom v1 dan v2
df = df.rename(columns=new_cols)

# cek data
df.head()

Labels                                            Message
0    ham  Go until jurong point, crazy.. Available only ...
1    ham                      Ok lar... Joking wif u oni...
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...
3    ham  U dun say so early hor... U c already then say...
4    ham  Nah I don't think he goes to usf, he lives aro...

<h4> Inspeksi data</h4>

In [20]:
# Cek Jumlah Data/kelas
print(df['Labels'].value_counts())
print('\n')
print(df.info())

print(df.describe())

ham     4825
spam     747
Name: Labels, dtype: int64


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Labels   5572 non-null   object
 1   Message  5572 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB
None
       Labels                 Message
count    5572                    5572
unique      2                    5169
top       ham  Sorry, I'll call later
freq     4825                      30


<h4>Melakukan encoding data dan membagi menjadi atribut dan target</h4>

In [21]:
# Melakukan encoding kategori
df['Labels'] = df['Labels'].map({'ham': 0, 'spam': 1})

# Memisahkan fitur dan target
X = df['Message'].values
y = df['Labels'].values

<h3>Fitur CountVectorizer dengan mengaktifkan stop_words</h3>

<h4>Membagi data menjadi data training dan data testing</h4>

In [22]:
# Membagi data menjadi data training (80%) dan data testing (20%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

<h4>Membuat Model Multinomial Naive Bayes dengan CountVectorizer</h4>

In [23]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline

# Membuat pipeline dengan CountVectorizer dan Multinomial Naive Bayes
pipeline = Pipeline([
    ('vectorizer', CountVectorizer(stop_words='english')),
    ('classifier', MultinomialNB())
])

# Melatih model
pipeline.fit(X_train, y_train)


Pipeline(steps=[('vectorizer', CountVectorizer(stop_words='english')),
                ('classifier', MultinomialNB())])

<h3>Evaluasi Hasil</h3>

In [24]:
# Memprediksi label untuk data pengujian
y_pred = pipeline.predict(X_test)

# Mengukur akurasi model
accuracy = accuracy_score(y_test, y_pred)
print("Akurasi Model Multinomial:", accuracy)

# Menampilkan laporan klasifikasi
print("Hasil Klasifikasi:")
print(classification_report(y_test, y_pred))

# Menampilkan matriks konfusi
print("Matriks Konfusi:")
print(confusion_matrix(y_test, y_pred))

Akurasi Model Multinomial: 0.9838565022421525
Hasil Klasifikasi:
              precision    recall  f1-score   support

           0       0.99      0.99      0.99       965
           1       0.96      0.92      0.94       150

    accuracy                           0.98      1115
   macro avg       0.97      0.96      0.96      1115
weighted avg       0.98      0.98      0.98      1115

Matriks Konfusi:
[[959   6]
 [ 12 138]]


In [26]:
# Inisiasi MultinomialNB
mnb = MultinomialNB()

# Memprediksi label untuk data pelatihan
y_train_pred = pipeline.predict(X_train)

# Mengukur akurasi model pada data pelatihan
train_accuracy = accuracy_score(y_train, y_train_pred)
print("Akurasi Model Multinomial Naive Bayes pada Data Pelatihan:", train_accuracy)

# Memprediksi label untuk data pengujian
y_test_pred = pipeline.predict(X_test)

# Mengukur akurasi model pada data pengujian
test_accuracy = accuracy_score(y_test, y_test_pred)
print("Akurasi Model Multinomial Naive Bayes pada Data Pengujian:", test_accuracy)

# Tingkat akurasi data training
acc_train = accuracy_score(y_train, y_train_pred)

# Tingkat akurasi data test
acc_test = accuracy_score(y_test, y_test_pred)

print(f'Hasil akurasi data train: {acc_train * 100:2f}%')
print(f'Hasil akurasi data test: {acc_test * 100:2f}%')

Akurasi Model Multinomial Naive Bayes pada Data Pelatihan: 0.9946152120260264
Akurasi Model Multinomial Naive Bayes pada Data Pengujian: 0.9838565022421525
Hasil akurasi data train: 99.461521%
Hasil akurasi data test: 98.385650%


<h2> 3. Buatlah model klasfikasi Multinomial Naive Bayes dengan ketentuan,</h2>

<h3>Menggunakan data spam.csv</h3>

In [28]:
# baca file CSV
df = pd.read_csv('../data/spam.csv', encoding='latin-1') 
df.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

<h4>Mengapus 3 kolom terakhir dan rename nama Kolom v1 dan v2</h4>

In [29]:
# Drop 3 kolom terakhir dengan fungsi iloc
df = df.drop(df.iloc[:,2:], axis=1)

# rename kolom v1 dan v2
new_cols = {
    'v1': 'Labels',
    'v2': 'Message'
}

# Rename nama kolom v1 dan v2
df = df.rename(columns=new_cols)

# cek data
df.head()

Labels                                            Message
0    ham  Go until jurong point, crazy.. Available only ...
1    ham                      Ok lar... Joking wif u oni...
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...
3    ham  U dun say so early hor... U c already then say...
4    ham  Nah I don't think he goes to usf, he lives aro...

<h4> Encoding dan memisahkan fitur dengan target

In [30]:
# Melakukan encoding kategori
df['Labels'] = df['Labels'].map({'ham': 0, 'spam': 1})

# Memisahkan fitur dan target
X = df['Message'].values
y = df['Labels'].values

<h3>Fitur TF-IDF dengan mengaktifkan stop_words</h3>

<h4>Membagi Data menjadi data testing dan data training</h4> 

In [31]:
# Membagi data menjadi data training (80%) dan data testing (20%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

<h4> Membuat Model Multinomial Naive Bayes dengan TF-IDF Vectorizer

In [32]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline

# Membuat pipeline dengan TfidfVectorizer dan Multinomial Naive Bayes
pipeline = Pipeline([
    ('vectorizer', TfidfVectorizer(stop_words='english')),
    ('classifier', MultinomialNB())
])

# Melatih model
pipeline.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', TfidfVectorizer(stop_words='english')),
                ('classifier', MultinomialNB())])

<h3>Evaluasi hasilnya dan bandingkan dengan hasil pada Tugas no 2.

<h4>Evaluasi Model dengan TF-IDF</h4>

In [33]:
# Memprediksi label untuk data pengujian
y_pred = pipeline.predict(X_test)

# Mengukur akurasi model dengan TF-IDF
accuracy_tfidf = accuracy_score(y_test, y_pred)
print("Akurasi Model Multinomial Naive Bayes dengan TF-IDF:", accuracy_tfidf)

# Menampilkan hasil klasifikasi dengan TF-IDF
print("\nLaporan Klasifikasi dengan TF-IDF:")
print(classification_report(y_test, y_pred))

# Menampilkan matriks konfusi dengan TF-IDF
print("\nMatriks Konfusi dengan TF-IDF:")
print(confusion_matrix(y_test, y_pred))

Akurasi Model Multinomial Naive Bayes dengan TF-IDF: 0.9677033492822966

Laporan Klasifikasi dengan TF-IDF:
              precision    recall  f1-score   support

           0       0.96      1.00      0.98      1453
           1       1.00      0.75      0.86       219

    accuracy                           0.97      1672
   macro avg       0.98      0.88      0.92      1672
weighted avg       0.97      0.97      0.97      1672


Matriks Konfusi dengan TF-IDF:
[[1453    0]
 [  54  165]]


In [34]:
# Memprediksi label untuk data training
y_train_pred = pipeline.predict(X_train)

# Mengukur akurasi model pada data traing
accuracy_train_tfidf = accuracy_score(y_train, y_train_pred)
print("Akurasi Model Multinomial Naive Bayes pada Data Training dengan TF-IDF:", accuracy_train_tfidf)

# Memprediksi label untuk data Testing
y_test_pred = pipeline.predict(X_test)

# Mengukur akurasi model dengan TF-IDF pada data Testing
accuracy_test_tfidf = accuracy_score(y_test, y_test_pred)
print("Akurasi Model Multinomial Naive Bayes pada Data Testing dengan TF-IDF:", accuracy_test_tfidf)

# Evaluasi akurasi data training
acc_train = accuracy_score(y_train, y_train_pred)

# Evaluasi akurasi data test
acc_test = accuracy_score(y_test, y_test_pred)

# Print hasil evaluasi
print(f'Hasil persentase akurasi data train: {acc_train * 100:f}%')
print(f'Hasil persentase akurasi data test: {acc_test * 100:f}%')

Akurasi Model Multinomial Naive Bayes pada Data Training dengan TF-IDF: 0.9823076923076923
Akurasi Model Multinomial Naive Bayes pada Data Testing dengan TF-IDF: 0.9677033492822966
Hasil persentase akurasi data train: 98.230769%
Hasil persentase akurasi data test: 96.770335%
